---
- name: Terraform Deployment Playbook
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Create S3 Bucket
      terraform:
        project_path: "{{ project_path }}"
        state: "{{ action_state }}"
        plan_file: "{{ plan_file }}"
