---
- name: Terraform Deployment Playbook
  gather_facts: false
  hosts: all
  tasks:
    - name: Set terraform backend configuration at initialization.
      terraform:
        project_path: "{{ project_path }}"
        state: "{{ action_state }}"
        force_init: "{{ force_init }}"
        backend_config:
          region: "{{ region }}"
          bucket: "{{ bucket_name }}"
          key: "{{ tfstate_filename }}.tfstate"

    - name: execute terraform apply and auto create plan file
      terraform:
        project_path: "{{ project_dir }}"
        state: "{{ action_state }}"
      # when: "{{ action_state }}" is present

    - name: execute terraform apply with existing plan file
      terraform:
        project_path: "{{ project_dir }}"
        state: "{{ action_state }}"
        plan_file: "{{ role_path }}/{{ plan_file_path }}"
      # when: "{{ action_state }}" is planned
